#!/bin/bash
echo ""
echo "-----------------------------------------------------------------------------------"
echo "List of commands:"
echo ""
echo ""
echo "bot-full-start      - After use this, confirm all components are running"
echo "bot-status          - Get a list of running components with process id"
echo ""
echo "start-OHLCV-check   - Start the OHLCV Check api"
echo "start-initial-list  - Start the Initial List script"
echo "start-reload        - Start the Reload script"
echo "start-pnl           - Start the Seller and trade management"
echo "start-buyer         - Start the Buyer"
echo "start-tg-balance    - Start the Telegram Balance script"
echo "start-tg-bot        - Start the Telegram Bot with commands"
echo ""
echo ""
echo "stop-pnl           - Stop the Seller and trade management"
echo "stop-buyer         - Stop the Buyer"
echo "stop-reload        - Stop the Reload script"
echo "stop-initial-list  - Stop the Initial List script"
echo "stop-OHLCV-check   - Stop the OHLCV Check api"
echo "stop-tg-balance    - Stop the Telegram Balance script"
echo "stop-tg-bot        - Stop the Telegram Bot with commands"
echo ""
echo ""
echo "sell-tracker       - Print sell_tracker.csv"
echo "open-orders        - Print open_orders_v2.csv"
echo ""
echo ""
echo "logs-buyer         - Display live logs for buyer"
echo "logs-pnl           - Display live logs for pnl"
echo "logs-ohlcv         - Display live logs for ohlcv"
echo "-----------------------------------------------------------------------------------"
echo ""
echo ""
